stages:
  - build
  - test

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t myflaskapp .

test:
  stage: test
  script:
    - docker run myflaskapp python -m unittest discover

